export const teachers = [
  {
    id: 1,
    name: "Dr. Eleanor Voss",
    age: 42,
    city: "Boston",
    subject: "Mathematics",
    phone: "+1 (617) 555-0142",
    email: "e.voss@edureview.edu",
    rating: 4.8,
    reviews: [
      {
        id: 1,
        author: "Alex M.",
        stars: 5,
        comment: "Dr. Voss has an incredible ability to make calculus feel intuitive. Her office hours are genuinely helpful.",
        date: "2025-11-03",
      },
      {
        id: 2,
        author: "Priya K.",
        stars: 5,
        comment: "Best math teacher I've ever had. Patient, thorough, and always brings real-world examples.",
        date: "2025-10-18",
      },
      {
        id: 3,
        author: "Tom R.",
        stars: 4,
        comment: "Challenging but fair. The workload is heavy, but you really learn the material.",
        date: "2025-09-30",
      },
    ],
    events: [
      { id: 1, title: "Calculus Exam Prep", date: "2026-03-10", time: "3:00 PM", type: "exam" },
      { id: 2, title: "Office Hours – Linear Algebra", date: "2026-02-25", time: "1:00 PM", type: "office" },
    ],
  },
  {
    id: 2,
    name: "Prof. Marcus Chen",
    age: 38,
    city: "San Francisco",
    subject: "Computer Science",
    phone: "+1 (415) 555-0289",
    email: "m.chen@edureview.edu",
    rating: 4.9,
    reviews: [
      {
        id: 1,
        author: "Jamie L.",
        stars: 5,
        comment: "Prof. Chen is literally the reason I fell in love with programming. His lectures are electric.",
        date: "2025-11-15",
      },
      {
        id: 2,
        author: "Sasha T.",
        stars: 5,
        comment: "Incredibly knowledgeable and always up to date with industry trends. A true mentor.",
        date: "2025-10-22",
      },
    ],
    events: [
      { id: 1, title: "Hackathon Kickoff", date: "2026-03-01", time: "10:00 AM", type: "workshop" },
      { id: 2, title: "Algorithm Study Session", date: "2026-02-28", time: "4:00 PM", type: "study" },
      { id: 3, title: "Guest Lecture: AI Ethics", date: "2026-03-15", time: "2:00 PM", type: "lecture" },
    ],
  },
  {
    id: 3,
    name: "Ms. Amara Osei",
    age: 35,
    city: "Chicago",
    subject: "Literature",
    phone: "+1 (312) 555-0374",
    email: "a.osei@edureview.edu",
    rating: 4.3,
    reviews: [
      {
        id: 1,
        author: "Ben W.",
        stars: 4,
        comment: "Ms. Osei brings stories alive in a way I never expected. She made me enjoy reading again.",
        date: "2025-11-08",
      },
      {
        id: 2,
        author: "Clara J.",
        stars: 5,
        comment: "Her analysis of postcolonial literature is unparalleled. Changed how I see the world.",
        date: "2025-10-05",
      },
      {
        id: 3,
        author: "Diego F.",
        stars: 4,
        comment: "Great discussions in class. Sometimes the essay requirements could be clearer.",
        date: "2025-09-12",
      },
    ],
    events: [
      { id: 1, title: "Poetry Workshop", date: "2026-03-05", time: "11:00 AM", type: "workshop" },
    ],
  },
  {
    id: 4,
    name: "Dr. Lena Fischer",
    age: 51,
    city: "Austin",
    subject: "Physics",
    phone: "+1 (512) 555-0461",
    email: "l.fischer@edureview.edu",
    rating: 3.9,
    reviews: [
      {
        id: 1,
        author: "Noah P.",
        stars: 4,
        comment: "Dr. Fischer knows her subject deeply. The labs are fascinating even if lectures can be dense.",
        date: "2025-11-20",
      },
      {
        id: 2,
        author: "Mei L.",
        stars: 3,
        comment: "Brilliant professor, but moves very fast. Definitely go to office hours.",
        date: "2025-10-14",
      },
    ],
    events: [],
  },
  {
    id: 5,
    name: "Mr. Sebastián Ruiz",
    age: 29,
    city: "Miami",
    subject: "History",
    phone: "+1 (305) 555-0598",
    email: "s.ruiz@edureview.edu",
    rating: 4.6,
    reviews: [
      {
        id: 1,
        author: "Anya B.",
        stars: 5,
        comment: "Mr. Ruiz is so passionate about history it's contagious. Best class of my semester!",
        date: "2025-11-25",
      },
      {
        id: 2,
        author: "Luke S.",
        stars: 4,
        comment: "Really engaging storyteller. Makes you feel like you're there in history.",
        date: "2025-10-30",
      },
    ],
    events: [
      { id: 1, title: "WWI Document Analysis", date: "2026-02-22", time: "9:00 AM", type: "study" },
      { id: 2, title: "Museum Field Trip", date: "2026-03-20", time: "8:30 AM", type: "lecture" },
    ],
  },
];
